### ISSUE TITLE
Incompatible with rubocop-0.47.0

### ISSUE THREAD

**Issue by madwort** [covermymeds/rubocop-thread_safety#10]
Just trying this out with the latest rubocop https://github.com/bbatsov/rubocop/releases/tag/v0.47.0 and getting a bunch of errors, maybe they've renamed some stuff and this plugin needs updating.

**Comment by mikegee** [comment]
@madwort I just released an update that should fix the problem. Please let me know if still have some problems and thanks a bunch for the feedback!

**Comment by madwort** [comment]
that works great, thanks @mikegee !
