### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by biow0lf** [covermymeds/rubocop-thread_safety#15]
Repository doesn't contain any information about license of project.

**Comment by mikegee** [comment]
Thanks for opening this issue, @biow0lf. I am looking into it now.

**Comment by tphoney** [comment]
👍

**Comment by mikegee** [comment]
I want to apply the [MIT License](https://opensource.org/licenses/MIT). Here are some reasons:

1. My intent releasing this project was to share it widely. I don't want users to be concerned about license restrictions.
1. Rubocop itself is licensed with the MIT License. It would be confusing/unexpected for an open source Rubocop plugin to be licensed differently than Rubocop.
1. The MIT License seems like a popular choice for the public repositories in this Github organization (my employer's). So I doubt I would violate any of my employer's policies by applying the MIT License to this project. @abwinkler999, can you confirm that?
1. Transitioning from unlicensed to the MIT License is unlikely to burden any users. (Transitioning to a license with more restrictions might be problematic.)

Let me know if you have any feedback or concerns. Thanks!
