### ISSUE TITLE
Enforce frozen class instance variables

### ISSUE THREAD

**Issue by tdeo** [covermymeds/rubocop-thread_safety#19]
Right now `ClassAndModuleAttributes` forbids `attr_writer` and `attr_accessor` on class instance variables. We should probably take this a step further and enforce frozen instance variables in this case (even if ruby doesn't have deep freezing).

The following code passes all the cops right now, even if its intended use is the same as an `attr_accessor`:
```ruby
class MyClass
  @my_variable = 'class instance variable'

  class << self
    attr_reader :my_variable
  end

  def self.my_method
    my_variable << ' modified'
  end
end

MyClass.my_method # => "class instance variable modified"
```

What do you think?

**Comment by mikegee** [comment]
> We should probably take this a step further and enforce frozen instance variables

I prefer to avoid these instance variables, but freezing them is a good compromise.

**Comment by biinari** [comment]
I've added a `MutableClassInstanceVariable` cop based on `MutableConstant`.

What do you think about tweaking it to allow thread-safe mutable objects like `Queue`, `Concurrent::Map` and `ThreadSafe::Hash`? Are there any other thread-safe mutable objects you can think of?

**Comment by mikegee** [comment]
I think allowing known thread-safe objects in `MutableClassInstanceVariable` makes perfect sense. That wouldn't need to be in the initial PR, in my opinion.
