### ISSUE TITLE
Show how to make it better as well

### ISSUE THREAD

**Issue by tmaier** [covermymeds/rubocop-thread_safety#20]
The comments of ghe cops show what kind of prectice is considered bad.

To improve it is alao relevant to understand what ia being considered the better practice.

Could you add examples or links to show how to do better in the comments?

**Comment by biinari** [comment]
Perhaps we can recommend some other ways to share state in the README, e.g.:
* Freeze objects assigned to class instance variables.
* `Thread.current[:var]` (though long-running threads may accumulate data over time if not cleaned up, growing in memory requirements)
* [RequestStore](https://github.com/steveklabnik/request_store)
* Use data structures or concurrency abstractions from [concurrent-ruby](https://github.com/ruby-concurrency/concurrent-ruby)
* Use a `Mutex` or similar for synchronization of access (noting the performance cost)
* Another idea I have also seen is a hash with `Thread.current.id` as the key. This seems prone to growing out of control if many threads are spawned and the hash doesn't get cleaned up. I am also unsure if a hash gives any guarantees for concurrent updates from different threads when the keys are known to differ.

There may even be some situations where the shared state is not actually needed and can be factored out.

I am also judging our own code based on whether shared state is only mutated in startup (before threads are spawned). Many class instance variables seem to be used solely for configuration, after which no further writes / mutations are made.

**Comment by biinari** [comment]
Maybe it is also worth noting that it is sensible to disable a cop with an in-code comment when it has been determined by the programmer that the usage is acceptable (never updated after threads launch or never used by threaded code).

For example:

```ruby
class Foo
  # rubocop:disable ThreadSafety/ClassAndModuleAttributes
  # These +settings+ are only ever written to during startup.
  cattr_accessor :settings
  # rubocop:enable ThreadSafety/ClassAndModuleAttributes
end
```
