### ISSUE TITLE
allow `instance_variable_set/get` in `define_method` context

### ISSUE THREAD

**Issue by michaelglass** [covermymeds/rubocop-thread_safety#37]
Howdy! Your gem is so great!

Just adding false positive we see:
https://github.com/railsbridge/bridge_troll/blob/76d67961c341ead6481d3046f7ac6428bd94efc8/app/models/concerns/presence_tracking_boolean.rb#L31-L34

simplified example:

```ruby
def self.foo
  define_method("foo") do
    instance_variable_get("@foo")
  end
end
```

My understanding is that the `instance_variable_get` above is actually executed within the instance context and shouldn't trigger rubocop.

❤️

**Comment by mikegee** [comment]
Thanks for the issue! That looks like a legit to false positive to me.

**Comment by r6e** [comment]
Submitted #48, which should address this and a related issue with `MutableClassInstanceVariable`. I'm not super-familiar with writing cops, so hopefully it meets the standard.
