### ISSUE TITLE
False Positive: ivar in dynamic method definition of class.new

### ISSUE THREAD

**Issue by SampsonCrowley** [covermymeds/rubocop-thread_safety#53]
Code:

```ruby
module QueryExtensions
  def self.ensure_where_not_chain(base)
    base.class_eval do
      const_get(:WhereNotChain)
    rescue NameError
      klass = Class.new {
        def initialize(scope)
          @scope = scope
        end
      }

      const_set(:WhereNotChain, klass)
    end
    base.const_get(:WhereNotChain)
  end
end
```

Results:
```
config/hooks/after_gems/03.query_extensions.rb:183:13: C: ThreadSafety/InstanceVariableInClassMethod: Avoid instance variables in class methods.
            @scope = scope
            ^^^^^^
```

The parser is detecting the method definition in the dynamically created class as having an instance variable in a class method. this is not the case. it is defining a method in the class and the instance variable is for an instance

**Comment by mikegee** [comment]
I agree this is a false positive. Thank you for the bug report!

**Comment by mikegee** [comment]
Development of this gem has been moved to [rubocop/rubocop-thread_safety](https://github.com/rubocop/rubocop-thread_safety). Would you kindly report this over there?

**Comment by SampsonCrowley** [comment]
Yes I can

**Comment by SampsonCrowley** [comment]
https://github.com/rubocop/rubocop-thread_safety/issues/28
